# fit the model and use it to make predictions

In [14]:
import pandas as pd

In [15]:
heart_disease = pd.read_csv('./Data/heart-disease.csv')

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

X_train, X_test, y_tarin, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

clf = RandomForestClassifier()

# fit the data
clf.fit(X_train,y_tarin)


clf.score(X_test,y_test)

0.8524590163934426


#### 2 ways to predict:
    1. predict()
    2. predict_proba()

In [17]:
y_preds = clf.predict(X_test)

import numpy as np
y_preds, np.array(y_test)

(array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64),
 array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
        0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64))

In [18]:
np.mean(y_preds == y_test)

0.8524590163934426

In [22]:
clf.predict_proba(X_test[:5])

array([[0.93, 0.07],
       [0.42, 0.58],
       [0.46, 0.54],
       [0.82, 0.18],
       [0.21, 0.79]])

In [21]:
df = pd.DataFrame(clf.predict_proba(X_test), columns=['class0','class1'])
df

class0  class1
0     0.93    0.07
1     0.42    0.58
2     0.46    0.54
3     0.82    0.18
4     0.21    0.79
..     ...     ...
56    0.65    0.35
57    0.02    0.98
58    0.91    0.09
59    1.00    0.00
60    0.89    0.11

[61 rows x 2 columns]

In [23]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

housing_df  = pd.DataFrame(housing['data'], columns=housing['feature_names'])
housing_df['target'] = housing['target']

X = housing_df.drop('target', axis = 1)
y = housing_df['target']

In [25]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

X_train, X_test, y_tarin, y_test = train_test_split(X,y, test_size=0.2)

model = RandomForestRegressor(n_estimators=200)
model.fit(X_train, y_tarin)


RandomForestRegressor(n_estimators=200)

In [26]:
y_preds = model.predict(X_test)

In [27]:
y_test2 = np.array(y_test) 

In [29]:
np.mean(np.absolute(y_preds-y_test2))

0.3264092437742251