In [10]:
import numpy as np
import pandas as pd

In [4]:
A1 = np.array([1,2,3])
A2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

A3 = np.array([[[1,2,3,],[2,3,4]],
               [[3,4,5],[4,5,6]]]
               )

In [8]:
A3.shape, A1.shape, A2.shape

((2, 2, 3), (3,), (3, 3))

In [9]:
A1.size,A2.size,A3.size

(3, 9, 12)

In [13]:
A2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
df = pd.DataFrame(A2)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

### Creating Arrays

In [15]:
ones = np.ones((2,3), dtype= int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
zeros = np.zeros((2,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
range_Arr = np.arange(0,10,2)
range_Arr

array([0, 2, 4, 6, 8])

In [20]:
random_arr = np.random.randint(0,10, size=(3,5))
random_arr

array([[6, 3, 7, 9, 2],
       [9, 8, 4, 8, 7],
       [6, 5, 9, 3, 9]])

In [23]:
random_arr_2 = np.random.random((3,5))
random_arr_2

array([[0.61531206, 0.94004503, 0.30912057, 0.79505646, 0.31825619],
       [0.74526067, 0.18440255, 0.12266132, 0.86145208, 0.95281044],
       [0.22245738, 0.18549662, 0.1451187 , 0.24499748, 0.68337786]])

In [34]:
np.random.seed(seed = 0)
random_arr_3 = np.random.random((5,3))
random_arr_3

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

### Viewing array

In [35]:
np.unique(random_arr)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
random_arr[2]

array([6, 5, 9, 3, 9])

In [37]:
range_Arr[3]

6

In [39]:
random_arr[:2,:2]

array([[6, 3],
       [9, 8]])

In [46]:
random_arr[:,:1]

array([[6],
       [9],
       [6]])

### Manipulating

##### Arithmetic

In [47]:
A1 + np.ones(3)

array([2., 3., 4.])

In [48]:
A1 * np.ones(3)

array([1., 2., 3.])

### Sorting Array

In [54]:
RandArr = np.random.randint(10, size = (3,5))
RandArr

array([[4, 3, 4, 4, 8],
       [4, 3, 7, 5, 5],
       [0, 1, 5, 9, 3]])

In [60]:
RandArr.argsort()


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [61]:
RandArr.argmax(axis= 1)

array([4, 4, 4], dtype=int64)

In [62]:
RandArr.argmax(axis= 0)

array([0, 0, 1, 1, 2], dtype=int64)

### Turn Images to Numpy Array

<img src='./numpy-images/panda.png'>

In [63]:
from matplotlib.image import imread

panda = imread("./numpy-images/panda.png")

In [65]:
type(panda)

numpy.ndarray

In [66]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

<img src="./numpy-images/car-photo.png">

In [68]:
car = imread("./numpy-images/car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352